import { itemsFromScraped } from "./scrapedItems";
import { seededRandom } from "./text";
import type { Category, Meal, MenuItem, ScrapedItem } from "./types";

export interface SamplePoolItem extends ScrapedItem {
  meals: Meal[];
}

const ALL: Meal[] = ["breakfast", "lunch", "brunch", "dinner"];
const LUNCH_DINNER: Meal[] = ["lunch", "brunch", "dinner"];
const BREAKFAST_BRUNCH: Meal[] = ["breakfast", "brunch"];

export const SAMPLE_POOL: SamplePoolItem[] = [
  {
    station: "Breakfast",
    name: "Scrambled Eggs",
    servingSize: "4 oz Serving (113g)",
    calories: 180,
    fiberGrams: 0,
    proteinGrams: 13,
    traits: ["Vegetarian"],
    allergens: ["Eggs"],
    meals: BREAKFAST_BRUNCH,
  },
  {
    station: "Breakfast",
    name: "Hard Cooked Eggs",
    servingSize: "2 Pieces (100g)",
    calories: 155,
    fiberGrams: 0,
    proteinGrams: 13,
    traits: ["Vegetarian"],
    allergens: ["Eggs"],
    meals: BREAKFAST_BRUNCH,
  },
  {
    station: "Breakfast",
    name: "Bacon",
    servingSize: "2 Slices (16g)",
    calories: 80,
    fiberGrams: 0,
    proteinGrams: 6,
    traits: [],
    allergens: [],
    meals: BREAKFAST_BRUNCH,
  },
  {
    station: "Breakfast",
    name: "Turkey Sausage Links",
    servingSize: "2 Links (56g)",
    calories: 110,
    fiberGrams: 0,
    proteinGrams: 10,
    traits: [],
    allergens: [],
    meals: BREAKFAST_BRUNCH,
  },
  {
    station: "Hot Cereal",
    name: "Oatmeal",
    servingSize: "1 Cup (234g)",
    calories: 160,
    fiberGrams: 4,
    proteinGrams: 6,
    traits: ["Vegan"],
    allergens: ["Oats"],
    meals: BREAKFAST_BRUNCH,
  },
  {
    station: "Hot Cereal",
    name: "Grits",
    servingSize: "1 Cup (233g)",
    calories: 145,
    fiberGrams: 2,
    proteinGrams: 3,
    traits: ["Vegan"],
    allergens: [],
    meals: BREAKFAST_BRUNCH,
  },
  {
    station: "Breakfast",
    name: "Blueberry Pancakes",
    servingSize: "2 Pancakes (120g)",
    calories: 250,
    fiberGrams: 2,
    proteinGrams: 6,
    traits: ["Vegetarian"],
    allergens: ["Wheat", "Eggs", "Milk"],
    meals: BREAKFAST_BRUNCH,
  },
  {
    station: "Breakfast",
    name: "Whole Wheat Toast",
    servingSize: "2 Slices (56g)",
    calories: 140,
    fiberGrams: 4,
    proteinGrams: 6,
    traits: ["Vegan"],
    allergens: ["Wheat"],
    meals: BREAKFAST_BRUNCH,
  },
  {
    station: "Fruit",
    name: "Seasonal Fruit",
    servingSize: "1/2 Cup (80g)",
    calories: 50,
    fiberGrams: 2,
    proteinGrams: 1,
    traits: ["Vegan"],
    allergens: [],
    meals: ALL,
  },
  {
    station: "Fruit",
    name: "Cantaloupe",
    servingSize: "1/2 Cup (80g)",
    calories: 30,
    fiberGrams: 1,
    proteinGrams: 1,
    traits: ["Vegan"],
    allergens: [],
    meals: BREAKFAST_BRUNCH,
  },
  {
    station: "Dairy",
    name: "Greek Yogurt",
    servingSize: "6 oz Serving (170g)",
    calories: 120,
    fiberGrams: 0,
    proteinGrams: 16,
    traits: ["Vegetarian"],
    allergens: ["Milk"],
    meals: BREAKFAST_BRUNCH,
  },
  {
    station: "Dairy",
    name: "Cottage Cheese",
    servingSize: "1/2 Cup (113g)",
    calories: 90,
    fiberGrams: 0,
    proteinGrams: 12,
    traits: ["Vegetarian"],
    allergens: ["Milk"],
    meals: BREAKFAST_BRUNCH,
  },
  {
    station: "Dairy",
    name: "Cheddar Cheese",
    servingSize: "1 oz Serving (28g)",
    calories: 110,
    fiberGrams: 0,
    proteinGrams: 7,
    traits: ["Vegetarian"],
    allergens: ["Milk"],
    meals: ALL,
  },
  {
    station: "Classics",
    name: "Lemon Herb Chicken",
    servingSize: "4 oz Serving (113g)",
    calories: 210,
    fiberGrams: 0,
    proteinGrams: 28,
    traits: [],
    allergens: [],
    meals: LUNCH_DINNER,
  },
  {
    station: "Classics",
    name: "Grilled Chicken Breast",
    servingSize: "4 oz Serving (113g)",
    calories: 190,
    fiberGrams: 0,
    proteinGrams: 32,
    traits: [],
    allergens: [],
    meals: LUNCH_DINNER,
  },
  {
    station: "Classics",
    name: "Baked Tofu",
    servingSize: "4 oz Serving (113g)",
    calories: 160,
    fiberGrams: 2,
    proteinGrams: 16,
    traits: ["Vegan"],
    allergens: ["Soy"],
    meals: LUNCH_DINNER,
  },
  {
    station: "Classics",
    name: "Turkey Meatballs",
    servingSize: "3 Pieces (90g)",
    calories: 200,
    fiberGrams: 1,
    proteinGrams: 18,
    traits: [],
    allergens: ["Wheat", "Eggs"],
    meals: LUNCH_DINNER,
  },
  {
    station: "Classics",
    name: "Beef Taco Filling",
    servingSize: "3 oz Serving (85g)",
    calories: 180,
    fiberGrams: 1,
    proteinGrams: 16,
    traits: [],
    allergens: [],
    meals: LUNCH_DINNER,
  },
  {
    station: "Halal",
    name: "Halal Chicken Thigh",
    servingSize: "4 oz Serving (113g)",
    calories: 230,
    fiberGrams: 0,
    proteinGrams: 24,
    traits: ["Halal"],
    allergens: [],
    meals: LUNCH_DINNER,
  },
  {
    station: "Classics",
    name: "Baked Salmon",
    servingSize: "4 oz Serving (113g)",
    calories: 240,
    fiberGrams: 0,
    proteinGrams: 23,
    traits: [],
    allergens: ["Fish"],
    meals: ["dinner", "brunch"],
  },
  {
    station: "Classics",
    name: "Pork Carnitas",
    servingSize: "3 oz Serving (85g)",
    calories: 210,
    fiberGrams: 0,
    proteinGrams: 18,
    traits: [],
    allergens: [],
    meals: LUNCH_DINNER,
  },
  {
    station: "Grill",
    name: "Black Bean Burger",
    servingSize: "1 Patty (113g)",
    calories: 220,
    fiberGrams: 8,
    proteinGrams: 14,
    traits: ["Vegan"],
    allergens: ["Wheat"],
    meals: LUNCH_DINNER,
  },
  {
    station: "24 Carrots",
    name: "Roasted Broccoli",
    servingSize: "1/2 Cup (80g)",
    calories: 55,
    fiberGrams: 3,
    proteinGrams: 3,
    traits: ["Vegan"],
    allergens: [],
    meals: LUNCH_DINNER,
  },
  {
    station: "24 Carrots",
    name: "Steamed Broccoli",
    servingSize: "1/2 Cup (78g)",
    calories: 30,
    fiberGrams: 2.5,
    proteinGrams: 2.5,
    traits: ["Vegan"],
    allergens: [],
    meals: LUNCH_DINNER,
  },
  {
    station: "24 Carrots",
    name: "Green Beans",
    servingSize: "1/2 Cup (80g)",
    calories: 35,
    fiberGrams: 3,
    proteinGrams: 2,
    traits: ["Vegan"],
    allergens: [],
    meals: ALL,
  },
  {
    station: "24 Carrots",
    name: "Roasted Carrots",
    servingSize: "1/2 Cup (80g)",
    calories: 45,
    fiberGrams: 3,
    proteinGrams: 1,
    traits: ["Vegan"],
    allergens: [],
    meals: LUNCH_DINNER,
  },
  {
    station: "24 Carrots",
    name: "Sauteed Kale",
    servingSize: "1 Cup (85g)",
    calories: 50,
    fiberGrams: 3,
    proteinGrams: 3,
    traits: ["Vegan"],
    allergens: [],
    meals: LUNCH_DINNER,
  },
  {
    station: "Salad",
    name: "Kale Salad",
    servingSize: "1 Cup (70g)",
    calories: 90,
    fiberGrams: 4,
    proteinGrams: 4,
    traits: ["Vegan"],
    allergens: [],
    meals: LUNCH_DINNER,
  },
  {
    station: "Salad",
    name: "Garden Salad",
    servingSize: "1.5 Cups (90g)",
    calories: 40,
    fiberGrams: 2,
    proteinGrams: 2,
    traits: ["Vegan"],
    allergens: [],
    meals: ALL,
  },
  {
    station: "Salad",
    name: "Chickpea Salad",
    servingSize: "1/2 Cup (100g)",
    calories: 150,
    fiberGrams: 6,
    proteinGrams: 7,
    traits: ["Vegan"],
    allergens: [],
    meals: LUNCH_DINNER,
  },
  {
    station: "Soup",
    name: "Tomato Basil Soup",
    servingSize: "8 oz serving (227g)",
    calories: 110,
    fiberGrams: 3,
    proteinGrams: 3,
    traits: ["Vegetarian"],
    allergens: ["Milk"],
    meals: LUNCH_DINNER,
  },
  {
    station: "Soup",
    name: "Chicken Noodle Soup",
    servingSize: "8 oz serving (227g)",
    calories: 130,
    fiberGrams: 2,
    proteinGrams: 9,
    traits: [],
    allergens: ["Wheat"],
    meals: LUNCH_DINNER,
  },
  {
    station: "Soup",
    name: "Vegetable Lentil Soup",
    servingSize: "8 oz serving (227g)",
    calories: 140,
    fiberGrams: 7,
    proteinGrams: 8,
    traits: ["Vegan"],
    allergens: [],
    meals: LUNCH_DINNER,
  },
  {
    station: "Starches",
    name: "Brown Rice",
    servingSize: "1/2 Cup (100g)",
    calories: 110,
    fiberGrams: 2,
    proteinGrams: 3,
    traits: ["Vegan"],
    allergens: [],
    meals: LUNCH_DINNER,
  },
  {
    station: "Starches",
    name: "White Rice",
    servingSize: "1/2 Cup (105g)",
    calories: 120,
    fiberGrams: 0.5,
    proteinGrams: 2,
    traits: ["Vegan"],
    allergens: [],
    meals: LUNCH_DINNER,
  },
  {
    station: "Starches",
    name: "Penne Pasta",
    servingSize: "1 Cup (140g)",
    calories: 200,
    fiberGrams: 2,
    proteinGrams: 7,
    traits: ["Vegan"],
    allergens: ["Wheat"],
    meals: LUNCH_DINNER,
  },
  {
    station: "Starches",
    name: "Mashed Potatoes",
    servingSize: "1/2 Cup (120g)",
    calories: 130,
    fiberGrams: 2,
    proteinGrams: 3,
    traits: ["Vegetarian"],
    allergens: ["Milk"],
    meals: LUNCH_DINNER,
  },
  {
    station: "Starches",
    name: "Roasted Potatoes",
    servingSize: "1/2 Cup (90g)",
    calories: 110,
    fiberGrams: 2,
    proteinGrams: 2,
    traits: ["Vegan"],
    allergens: [],
    meals: ALL,
  },
  {
    station: "Starches",
    name: "Quinoa Pilaf",
    servingSize: "1/2 Cup (90g)",
    calories: 110,
    fiberGrams: 3,
    proteinGrams: 4,
    traits: ["Vegan"],
    allergens: [],
    meals: LUNCH_DINNER,
  },
  {
    station: "Pizziti",
    name: "Cheese Pizza",
    servingSize: "1 Slice (105g)",
    calories: 260,
    fiberGrams: 2,
    proteinGrams: 12,
    traits: ["Vegetarian"],
    allergens: ["Wheat", "Milk"],
    meals: LUNCH_DINNER,
  },
  {
    station: "Pizziti",
    name: "Vegetable Pizza",
    servingSize: "1 Slice (113g)",
    calories: 240,
    fiberGrams: 3,
    proteinGrams: 10,
    traits: ["Vegetarian"],
    allergens: ["Wheat", "Milk"],
    meals: LUNCH_DINNER,
  },
  {
    station: "Deli",
    name: "Turkey Sandwich",
    servingSize: "1 Sandwich (180g)",
    calories: 320,
    fiberGrams: 3,
    proteinGrams: 22,
    traits: [],
    allergens: ["Wheat"],
    meals: ["lunch", "brunch"],
  },
  {
    station: "Breakfast",
    name: "Spinach Egg Bake",
    servingSize: "1 Piece (120g)",
    calories: 180,
    fiberGrams: 1,
    proteinGrams: 12,
    traits: ["Vegetarian"],
    allergens: ["Eggs", "Milk"],
    meals: BREAKFAST_BRUNCH,
  },
  {
    station: "Breakfast",
    name: "Tofu Scramble",
    servingSize: "4 oz Serving (113g)",
    calories: 150,
    fiberGrams: 2,
    proteinGrams: 14,
    traits: ["Vegan"],
    allergens: ["Soy"],
    meals: BREAKFAST_BRUNCH,
  },
  {
    station: "24 Carrots",
    name: "Roasted Cauliflower",
    servingSize: "1/2 Cup (75g)",
    calories: 40,
    fiberGrams: 2,
    proteinGrams: 2,
    traits: ["Vegan"],
    allergens: [],
    meals: LUNCH_DINNER,
  },
  {
    station: "24 Carrots",
    name: "Corn",
    servingSize: "1/2 Cup (80g)",
    calories: 70,
    fiberGrams: 2,
    proteinGrams: 2,
    traits: ["Vegan"],
    allergens: ["Corn"],
    meals: LUNCH_DINNER,
  },
  {
    station: "Classics",
    name: "BBQ Chicken",
    servingSize: "4 oz Serving (113g)",
    calories: 220,
    fiberGrams: 0,
    proteinGrams: 26,
    traits: [],
    allergens: [],
    meals: LUNCH_DINNER,
  },
  {
    station: "Starches",
    name: "Macaroni and Cheese",
    servingSize: "1/2 Cup (120g)",
    calories: 220,
    fiberGrams: 1,
    proteinGrams: 8,
    traits: ["Vegetarian"],
    allergens: ["Wheat", "Milk"],
    meals: LUNCH_DINNER,
  },
  {
    station: "Dairy",
    name: "Vanilla Yogurt",
    servingSize: "4 oz Serving (113g)",
    calories: 90,
    fiberGrams: 0,
    proteinGrams: 5,
    traits: ["Vegetarian"],
    allergens: ["Milk"],
    meals: BREAKFAST_BRUNCH,
  },
  {
    station: "Fruit",
    name: "Apple Slices",
    servingSize: "1/2 Cup (55g)",
    calories: 30,
    fiberGrams: 1.5,
    proteinGrams: 0,
    traits: ["Vegan"],
    allergens: [],
    meals: ALL,
  },
  {
    station: "Classics",
    name: "Herb Baked Tofu",
    servingSize: "4 oz Serving (113g)",
    calories: 155,
    fiberGrams: 2,
    proteinGrams: 15,
    traits: ["Vegan"],
    allergens: ["Soy"],
    meals: ["brunch", "dinner"],
  },
  {
    station: "24 Carrots",
    name: "Roasted Brussels Sprouts",
    servingSize: "1/2 Cup (80g)",
    calories: 50,
    fiberGrams: 3,
    proteinGrams: 3,
    traits: ["Vegan"],
    allergens: [],
    meals: ["dinner", "brunch"],
  },
];

const CATEGORIES: Category[] = ["Protein", "Produce", "Grains", "Dairy"];

export function buildSampleMenu(
  hallId: string,
  date: string,
  meal: Meal,
  cap = 12,
): MenuItem[] {
  const rand = seededRandom(`sample|${hallId}|${date}|${meal}`);
  const eligible = SAMPLE_POOL.filter((p) => p.meals.includes(meal));
  const converted = itemsFromScraped(hallId, eligible, eligible.length);
  const shuffle = <T,>(list: T[]) => {
    const copy = [...list];
    for (let i = copy.length - 1; i > 0; i--) {
      const j = Math.floor(rand() * (i + 1));
      [copy[i], copy[j]] = [copy[j], copy[i]];
    }
    return copy;
  };
  const byCat = new Map<Category, MenuItem[]>();
  for (const item of converted) {
    const list = byCat.get(item.category) ?? [];
    list.push(item);
    byCat.set(item.category, list);
  }
  const picked: MenuItem[] = [];
  const used = new Set<string>();
  for (const cat of CATEGORIES) {
    const pool = shuffle(byCat.get(cat) ?? []);
    let n = 0;
    for (const item of pool) {
      if (n >= 2 || picked.length >= cap) break;
      if (used.has(item.id)) continue;
      picked.push(item);
      used.add(item.id);
      n += 1;
    }
  }
  const rest = shuffle(converted.filter((i) => !used.has(i.id)));
  for (const item of rest) {
    if (picked.length >= cap) break;
    picked.push(item);
    used.add(item.id);
  }
  return picked.slice(0, cap);
}
